### PR TITLE
Fixes from nephila/django-cms-themes

### PR DESCRIPTION
**Pull request by notexeditor**
Hi Mark,

I took the liberty to send you [_nephila_'s fixes](https://github.com/nephila/django-cms-themes) as a pull request. I'd trouble with issue [#3](https://github.com/MegaMark16/django-cms-themes/issues/3) which _nephila_ seems to have fixed, but I did not see any corresponding pull request from his side.

In addition have added one "fix" on my own which tells the OS environment to use Python 2 instead of Python 3; I don't know if some (older) setups will have trouble with

```
#!/usr/bin/env python2
```

but if so just ignore my related commit 95af1be2d31685eca899549fe9656b137cedcf96.

### CODE REVIEW

**Comment by yakky** [comment]
Yes, basically i didn't requested pull for the commits because i feel it's a very ugly hack, but I haven't had time to find a better solution since then.

**Comment by notexeditor** [comment]
So you think I should close the pull request? Still think your tweak has value .. it solved my problem.

**Comment by yakky** [comment]
I'm still +1
I commited because it solves a problem, and it's one step in the right direction.
So I do hope MegaMark16 would accept this.

**Comment by MegaMark16** [comment]
Thanks @hsk81 and @nephila, sorry it took so long for me to get around to merging the fix, but it works like a charm, and honestly the whole thing is kind of a hack, so it fits right in :-)  

Thanks!
Mark

**Pull request merged**
